### ISSUE TITLE
Bitshares link 404

### ISSUE THREAD

**Issue by nuke-web3** [EthereumOpenSubscriptions/awesome-blockchain-subscriptions#1]
https://bitshares.org/technology/recurring-and-scheduled-payments/ is broke :cry:

**Comment by nuke-web3** [comment]
https://bitshares.org/technology/recurring-scheduled-payments/
Still broke @PaulRBerg

**Comment by PaulRBerg** [comment]
Oh wow so if you add a `/`, the link's broken. Poor path handling.

**Comment by nuke-web3** [comment]
:man_facepalming: ug. thanks for the fix!
